[mongodb]
mongodb-dev.daws88.sbs

[catalogue]
catalogue-dev.daws88.sbs

[redis]
redis-dev.daws88.sbs

[user]
user-dev.daws88.sbs

[cart]
cart-dev.daws88.sbs

[all:vars]
ansible_user= ec2-user
ansible_password= DevOps321
MONGODB_HOST=mongodb-dev.daws88.sbs
CATALOGUE_HOST=catalogue-dev.daws88.sbs
REDIS_HOST=redis-dev.daws88.sbs
USER_HOST=user-dev.daws88.sbs